update module (#2)
* update module, add travis , fix warnings

* add dry-run

* update cmake

* fix cmake

* typo

* update fix travis error , fatal error: use of undeclared identifier 'ChatHandler'
            ChatHandler(player->GetSession()).SendSysMessage("This server is running the |cff4CFF00Level Item |rmodule.");
            ^

* update conf

* update readme add credits

* update add line break

* Fixing indentation

* Fixing SQL

This will help db_assembler so it won't throw errors.

Look here for more info regarding how to write SQL code:
http://www.azerothcore.org/wiki/Dealing-with-SQL-files

* Removed hardcoded level message

Co-authored-by: WiZZy <bilucristian25@gmail.com>